# plot_fast_charger.py
# this code was generated by FhGenie

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def _as_bool(values: pd.Series) -> pd.Series:
    """Convert CSV-compatible boolean values to booleans."""
    if pd.api.types.is_bool_dtype(values):
        return values.fillna(False).astype(bool)

    return (
        values.astype("string")
        .str.strip()
        .str.lower()
        .isin({"true", "1", "yes", "ja"})
    )


def _step_plot(
    axis,
    timestamps: pd.Series,
    values: pd.Series,
    time_delta: pd.Timedelta,
    **kwargs,
) -> None:
    """Draw a piecewise-constant power series including the final interval."""
    if timestamps.empty:
        return

    x_values = timestamps.tolist()
    y_values = values.tolist()

    x_values.append(x_values[-1] + time_delta)
    y_values.append(y_values[-1])

    axis.step(x_values, y_values, where="post", **kwargs)


def _session_colors(
    session_ids: list[int],
) -> dict[int, tuple[float, float, float, float]]:
    """Return one consistent RGBA color per charging session."""
    if not session_ids:
        return {}

    if len(session_ids) <= 20:
        color_map = plt.get_cmap("tab20")
        number_of_colors = 20
    else:
        color_map = plt.get_cmap("hsv")
        number_of_colors = len(session_ids)

    return {
        session_id: color_map((index + 0.5) / number_of_colors)
        for index, session_id in enumerate(session_ids)
    }


def main() -> None:
    """Create a fast-charger simulation plot from a results CSV file."""
    parser = argparse.ArgumentParser(
        description="Create a plot for fast-charger simulation results.",
    )
    parser.add_argument(
        "--results",
        type=Path,
        default=Path("results/simulation_results.csv"),
        help="Path to the simulation results CSV file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/fast_charger_plot.png"),
        help="Output image path.",
    )
    parser.add_argument(
        "--charge-point",
        default="charge_point1",
        help="Charge-point label used in the simulation.",
    )
    parser.add_argument(
        "--storage",
        default="battery",
        help="Stationary battery label used in the simulation.",
    )
    parser.add_argument(
        "--grid-column",
        default="grid_builder_usage",
        help="Column containing the grid power.",
    )
    parser.add_argument(
        "--start",
        default=None,
        help="Optional start timestamp, e.g. '2021-01-01'.",
    )
    parser.add_argument(
        "--end",
        default=None,
        help="Optional end timestamp, e.g. '2021-01-08'.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the plot after saving it.",
    )
    args = parser.parse_args()

    columns = {
        "connected": (
            f"components_states.{args.charge_point}.ev_connected"
        ),
        "ev_soc": f"components_states.{args.charge_point}.ev_soc",
        "storage_soc": f"components_states.{args.storage}.soc",
        "ev_power": f"power_applied.{args.charge_point}",
        "storage_power": f"power_applied.{args.storage}",
        "grid_power": args.grid_column,
    }

    results = pd.read_csv(args.results, sep=None, engine="python")

    required_columns = ["date_time", *columns.values()]
    missing_columns = [
        column for column in required_columns
        if column not in results.columns
    ]
    if missing_columns:
        raise ValueError(
            "The following columns are missing from the results file: "
            + ", ".join(missing_columns),
        )

    results["date_time"] = pd.to_datetime(
        results["date_time"],
        errors="raise",
    )

    for key in (
        "ev_soc",
        "storage_soc",
        "ev_power",
        "storage_power",
        "grid_power",
    ):
        results[columns[key]] = pd.to_numeric(
            results[columns[key]],
            errors="coerce",
        )

    results = results.sort_values("date_time").reset_index(drop=True)

    # A contiguous ev_connected=True period represents one charging session.
    results["_ev_connected"] = _as_bool(results[columns["connected"]])
    previous_connected = results["_ev_connected"].shift(
        1,
        fill_value=False,
    )
    session_starts = results["_ev_connected"] & ~previous_connected

    results["_session_id"] = (
        session_starts.cumsum()
        .where(results["_ev_connected"])
    )

    # Determine sessions before filtering the time range so that a session
    # already in progress at the left boundary is retained.
    if args.start:
        results = results.loc[
            results["date_time"] >= pd.Timestamp(args.start)
        ]

    if args.end:
        results = results.loc[
            results["date_time"] <= pd.Timestamp(args.end)
        ]

    results = results.copy()

    if results.empty:
        raise ValueError("No data is available for the selected time range.")

    time_deltas = results["date_time"].diff().dropna()
    time_deltas = time_deltas[time_deltas > pd.Timedelta(0)]

    time_delta: pd.Timedelta = pd.Timedelta(minutes=15)

    if not time_deltas.empty:
        median_delta: object = time_deltas.median()

        if not isinstance(median_delta, pd.Timedelta):
            raise TypeError(
                "The time interval between result rows could not be "
                "determined as a pandas.Timedelta.",
            )

        time_delta = median_delta

    session_ids = [
        int(session_id)
        for session_id in results.loc[
            results["_ev_connected"],
            "_session_id",
        ].dropna().unique()
    ]

    sessions = {
        session_id: results.loc[
            results["_session_id"] == session_id
        ]
        for session_id in session_ids
    }
    colors = _session_colors(session_ids)

    fig, (ax_soc, ax_power, ax_grid) = plt.subplots(
        nrows=3,
        ncols=1,
        figsize=(16, 11),
        sharex=True,
    )

    axes = (ax_soc, ax_power, ax_grid)

    # Shade periods during which the charge point is occupied.
    for session_id, session in sessions.items():
        start = session["date_time"].iloc[0]
        end = session["date_time"].iloc[-1] + time_delta

        for axis in axes:
            axis.axvspan(
                start,
                end,
                color=colors[session_id],
                alpha=0.10,
                linewidth=0,
                zorder=0,
            )

    # Stationary battery state of charge.
    ax_soc.plot(
        results["date_time"],
        100.0 * results[columns["storage_soc"]],
        color="black",
        linewidth=2.0,
        label="Stationary battery",
        zorder=3,
    )

    # EV state of charge for each charging session.
    show_ev_legend = len(session_ids) <= 12

    for session_id, session in sessions.items():
        label = f"EV {session_id}" if show_ev_legend else None

        ax_soc.plot(
            session["date_time"],
            100.0 * session[columns["ev_soc"]],
            color=colors[session_id],
            linewidth=1.8,
            label=label,
            zorder=4,
        )

    # Stationary battery power.
    _step_plot(
        ax_power,
        results["date_time"],
        results[columns["storage_power"]],
        time_delta,
        color="black",
        linestyle="--",
        linewidth=1.8,
        label="Stationary battery",
        zorder=3,
    )

    # EV power for each charging session.
    for session_id, session in sessions.items():
        label = f"EV {session_id}" if show_ev_legend else None

        _step_plot(
            ax_power,
            session["date_time"],
            session[columns["ev_power"]],
            time_delta,
            color=colors[session_id],
            linewidth=1.6,
            label=label,
            zorder=4,
        )

    # Grid power.
    _step_plot(
        ax_grid,
        results["date_time"],
        results[columns["grid_power"]],
        time_delta,
        color="tab:green",
        linewidth=1.8,
        label="Grid connection",
        zorder=3,
    )

    ax_soc.set_ylabel("SoC [%]")
    ax_soc.set_ylim(-5, 105)

    ax_power.set_ylabel("Power [kW]\n(+ Discharging / - Charging)")
    ax_grid.set_ylabel("Grid power [kW]\n(+ Import / - Export)")
    ax_grid.set_xlabel("Time")

    for axis in (ax_power, ax_grid):
        axis.axhline(0.0, color="gray", linewidth=0.8, zorder=1)

    x_min = results["date_time"].iloc[0]
    x_max = results["date_time"].iloc[-1] + time_delta

    for axis in axes:
        axis.set_xlim(x_min, x_max)
        axis.grid(True, axis="y", alpha=0.3)
        axis.set_axisbelow(True)

        handles, _ = axis.get_legend_handles_labels()
        if handles:
            axis.legend(
                loc="upper left",
                fontsize=8,
                ncol=2 if len(handles) > 1 else 1,
            )

    fig.suptitle(
        f"Fast charging point {args.charge_point} "
        f"({len(session_ids)} visible charging sessions)",
        fontsize=14,
    )
    fig.text(
        0.01,
        0.01,
        "Colored background areas indicate periods during which the charge "
        "point is occupied. The same color represents the same charging "
        "session.",
        fontsize=8,
    )

    fig.autofmt_xdate(rotation=30, ha="right")
    fig.tight_layout(rect=(0, 0.035, 1, 0.96))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.output, dpi=200, bbox_inches="tight")

    print(f"Plot saved: {args.output.resolve()}")

    if args.show:
        plt.show()

    plt.close(fig)


if __name__ == "__main__":
    main()
