from nrgise.economics.behind_the_meter.electricity_bill_calculator.data_classes import GridTariff
from nrgise.economics.behind_the_meter.electricity_bill_calculator.main import calculate_electricity_bill
